title: 'Kent Bayron'
description: "Tech Blog"
baseurl: "/"
url: "https://kentbayron.github.io"

header_pages:
  - index.md
  - projects.md
  - about.md

style: hacker

footer: 'follow me on <a href="https://twitter.com/bayronkentoy">twitter</a>'
google_analytics: G-RTCZ8Q61PV

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

